In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv("dead_vital_sign_total_new_fillna_and_drop.csv")
print(df)

       subject_id   stay_id            indextime                 date  \
0        10001884  37510196  2131-01-20 04:19:00  2131-01-19 05:19:00
1        10001884  37510196  2131-01-20 04:19:00  2131-01-19 06:19:00
2        10001884  37510196  2131-01-20 04:19:00  2131-01-19 07:19:00
3        10001884  37510196  2131-01-20 04:19:00  2131-01-19 08:19:00
4        10001884  37510196  2131-01-20 04:19:00  2131-01-19 09:19:00
...           ...       ...                  ...                  ...
86897    19999840  38978960  2164-09-17 13:39:00  2164-09-17 09:39:00
86898    19999840  38978960  2164-09-17 13:39:00  2164-09-17 10:39:00
86899    19999840  38978960  2164-09-17 13:39:00  2164-09-17 11:39:00
86900    19999840  38978960  2164-09-17 13:39:00  2164-09-17 12:39:00
86901    19999840  38978960  2164-09-17 13:39:00  2164-09-17 13:39:00

       heart_rate  resp_rate    sbp   dbp   mbp  spo2  hours_diff
0            68.0       19.0  138.0  77.0  96.0  99.0          23
1            65.0       19.0  121.0  73.0  87.0  97.0          22
2            63.0       18.0  123.0  72.0  86.0  97.0          21
3            63.0       20.0  125.0  74.0  90.0  97.0          20
4            66.0       19.0  107.0  67.0  79.0  97.0          19
...           ...        ...    ...   ...   ...   ...         ...
86897        60.0       26.0   99.0  47.0  56.0  95.0           4
86898        61.0       23.0  111.0  52.0  66.0  96.0           3
86899        63.0       24.0  108.0  57.0  67.0  92.0           2
86900        76.0       24.0  111.0  53.0  65.0  92.0           1
86901        74.0       29.0   61.0  48.0  44.0  98.0           0

[86902 rows x 11 columns]

In [2]:
df_new_1=df.subject_id.value_counts().index[:3676]  
print(df_new_1)

Int64Index([14950396, 17632313, 13719090, 14083588, 15259074, 12844455,
            14351751, 16858495, 18554235, 16747881,
            ...
            18624988, 10688510, 10929752, 18003764, 15163376, 14623418,
            17159783, 14677796, 11966608, 12974812],
           dtype='int64', length=3676)

In [3]:
df_new_2=df.subject_id.value_counts().index[-28:]
print(df_new_2)

Int64Index([19650110, 13911200, 14042090, 12935309, 10247549, 10559377,
            14385971, 19637282, 18310386, 16827838, 17030222, 18190935,
            16783338, 17127038, 17511838, 13488954, 15693895, 14357885,
            11372975, 12151776, 15720091, 18985506, 19232176, 14110658,
            19440249, 14899599, 11434633, 15724368],
           dtype='int64')

In [5]:
print(df)

       subject_id   stay_id            indextime                 date  \
0        10001884  37510196  2131-01-20 04:19:00  2131-01-19 05:19:00
1        10001884  37510196  2131-01-20 04:19:00  2131-01-19 06:19:00
2        10001884  37510196  2131-01-20 04:19:00  2131-01-19 07:19:00
3        10001884  37510196  2131-01-20 04:19:00  2131-01-19 08:19:00
4        10001884  37510196  2131-01-20 04:19:00  2131-01-19 09:19:00
...           ...       ...                  ...                  ...
86897    19999840  38978960  2164-09-17 13:39:00  2164-09-17 09:39:00
86898    19999840  38978960  2164-09-17 13:39:00  2164-09-17 10:39:00
86899    19999840  38978960  2164-09-17 13:39:00  2164-09-17 11:39:00
86900    19999840  38978960  2164-09-17 13:39:00  2164-09-17 12:39:00
86901    19999840  38978960  2164-09-17 13:39:00  2164-09-17 13:39:00

       heart_rate  resp_rate    sbp   dbp   mbp  spo2  hours_diff
0            68.0       19.0  138.0  77.0  96.0  99.0          23
1            65.0       19.0  121.0  73.0  87.0  97.0          22
2            63.0       18.0  123.0  72.0  86.0  97.0          21
3            63.0       20.0  125.0  74.0  90.0  97.0          20
4            66.0       19.0  107.0  67.0  79.0  97.0          19
...           ...        ...    ...   ...   ...   ...         ...
86897        60.0       26.0   99.0  47.0  56.0  95.0           4
86898        61.0       23.0  111.0  52.0  66.0  96.0           3
86899        63.0       24.0  108.0  57.0  67.0  92.0           2
86900        76.0       24.0  111.0  53.0  65.0  92.0           1
86901        74.0       29.0   61.0  48.0  44.0  98.0           0

[86902 rows x 11 columns]

In [6]:
df_new=df[df.subject_id.isin(list(df_new_1))]
print(df_new)
#df_new.to_csv("dead_vital_sign_total_new_del_miss.csv",index=False)

       subject_id   stay_id            indextime                 date  \
0        10001884  37510196  2131-01-20 04:19:00  2131-01-19 05:19:00
1        10001884  37510196  2131-01-20 04:19:00  2131-01-19 06:19:00
2        10001884  37510196  2131-01-20 04:19:00  2131-01-19 07:19:00
3        10001884  37510196  2131-01-20 04:19:00  2131-01-19 08:19:00
4        10001884  37510196  2131-01-20 04:19:00  2131-01-19 09:19:00
...           ...       ...                  ...                  ...
86897    19999840  38978960  2164-09-17 13:39:00  2164-09-17 09:39:00
86898    19999840  38978960  2164-09-17 13:39:00  2164-09-17 10:39:00
86899    19999840  38978960  2164-09-17 13:39:00  2164-09-17 11:39:00
86900    19999840  38978960  2164-09-17 13:39:00  2164-09-17 12:39:00
86901    19999840  38978960  2164-09-17 13:39:00  2164-09-17 13:39:00

       heart_rate  resp_rate    sbp   dbp   mbp  spo2  hours_diff
0            68.0       19.0  138.0  77.0  96.0  99.0          23
1            65.0       19.0  121.0  73.0  87.0  97.0          22
2            63.0       18.0  123.0  72.0  86.0  97.0          21
3            63.0       20.0  125.0  74.0  90.0  97.0          20
4            66.0       19.0  107.0  67.0  79.0  97.0          19
...           ...        ...    ...   ...   ...   ...         ...
86897        60.0       26.0   99.0  47.0  56.0  95.0           4
86898        61.0       23.0  111.0  52.0  66.0  96.0           3
86899        63.0       24.0  108.0  57.0  67.0  92.0           2
86900        76.0       24.0  111.0  53.0  65.0  92.0           1
86901        74.0       29.0   61.0  48.0  44.0  98.0           0

[86681 rows x 11 columns]

In [9]:
print(df_new.stay_id.value_counts().index[:])  

aa=df_new.stay_id.value_counts().index[:]
aa=aa.to_frame()
aa.to_csv("aa_stay.csv",index=False)

Int64Index([38668223, 33125433, 30508327, 37076256, 31636736, 36637942,
            33158313, 37850278, 39558308, 37225623,
            ...
            33252495, 37045237, 31559071, 35583532, 34133437, 39124077,
            35665841, 33140628, 39624607, 36323016],
           dtype='int64', length=3676)

In [ ]:
#df_new_1=df_new_1.to_frame()
#df_new_1.to_csv("a1.csv",index=False)
#df_new_2=df_new_2.to_frame()
#df_new_2.to_csv("a2.csv",index=False)

In [3]:
print(df.subject_id.value_counts())

14950396    24
17632313    24
13719090    24
14083588    24
15259074    24
            ..
14110658     5
19440249     4
14899599     3
11434633     3
15724368     2
Name: subject_id, Length: 3704, dtype: int64

In [4]:
print(df.subject_id.value_counts().value_counts())

24    2994
23     336
22     166
21      66
20      48
19      16
16      13
18      10
14       8
17       8
15       8
7        5
10       5
12       4
6        3
13       3
11       2
9        2
3        2
5        2
8        1
4        1
2        1
Name: subject_id, dtype: int64